version: '3.5'
services:
  web:
    build:
      context: ./containers/php
    container_name: yolohome-web
    image: yolohome-web
    volumes:
      - ../:/var/www/yolohome
      - ./containers/php/nginx.conf:/etc/nginx/conf.d/server.conf
    environment:
      - APP_ENV=${APP_ENV:-local}
    ports:
      - 80:80
    depends_on:
      - mysql
      - redis
    networks:
      - yolohome-net
    restart: on-failure

  mysql:
    build:
      context: ./containers/mysql
    container_name: yolohome-mysql
    image: yolohome-mysql
    volumes:
      - yolohome-mysql-vol:/var/lib/mysql
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
    ports:
      - "3306:3306"
    networks:
      - yolohome-net
    restart: on-failure

  redis:
    build:
      context: ./containers/redis
    container_name: yolohome-redis
    image: yolohome-redis
    ports:
      - "6379:6379"
    volumes:
      - yolohome-redis-vol:/var/lib/redis/
    networks:
      - yolohome-net
    restart: on-failure

networks:
  yolohome-net:

volumes:
  yolohome-mysql-vol:
  yolohome-redis-vol:
